version: '3.3'

services:
    userdb:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: OSM_USER_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: school123
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 33306:3306
        volumes: 
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
