version: '3.3'

services:
    mysql_user_db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: OSM_USER_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: school123
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes: 
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    mongo_user_eventstore:
        image: 'bitnami/mongodb:latest'
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGODB_USERNAME=mongouser
            - MONGODB_PASSWORD=school123
            - MONGODB_DATABASE=OSM_USER_EVENTS
